---
deployment:
  environment:
    VENV_ACTIVATION_PATH: /home/cme26486/nodevenv/app/cmed-server/16/bin/activate
    DEPLOYPATH: /home/cme26486/app/cmed-server
  tasks:
    - source $VENV_ACTIVATION_PATH && npm run build
    - if [ -d $DEPLOYPATH/dist ]; then rm -rf $DEPLOYPATH/dist; fi
    - if [ -f $DEPLOYPATH/package.json ]; then rm $DEPLOYPATH/package.json; fi
    - cp -r dist $DEPLOYPATH
    - cp package.json $DEPLOYPATH
