---
deployment:
  environment:
    VENV_ACTIVATION_PATH: $VENV_ACTIVATION_PATH
    DEPLOYPATH: $DEPLOYPATH
  tasks:
    - source $VENV_ACTIVATION_PATH && npm run build
    - if [ -d $DEPLOYPATH/dist ]; then rm -rf $DEPLOYPATH/dist; fi
    - if [ -f $DEPLOYPATH/package.json ]; then rm $DEPLOYPATH/package.json; fi
    - cp -r dist $DEPLOYPATH
    - cp package.json $DEPLOYPATH
